# Generated by Django 2.2.5 on 2020-01-01 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0002_applyleave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyleave',
            name='user',
        ),
    ]
